openapi: 3.0.3
info:
  title: PollCraft API
  version: 1.0.0
  description: Server API for registration, profiles and poll management.
paths:
  /api/about/:
    get:
      operationId: about_retrieve
      tags:
      - about
      security:
      - tokenAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AboutApp'
          description: ''
  /api/auth/login/:
    post:
      operationId: auth_login_create
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Login'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Login'
        required: true
      security:
      - tokenAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
          description: ''
  /api/auth/profile/:
    get:
      operationId: auth_profile_retrieve
      tags:
      - auth
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
          description: ''
    put:
      operationId: auth_profile_update
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserProfile'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserProfile'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserProfile'
        required: true
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
          description: ''
    patch:
      operationId: auth_profile_partial_update
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedUserProfile'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedUserProfile'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedUserProfile'
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
          description: ''
  /api/auth/register/:
    post:
      operationId: auth_register_create
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Register'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Register'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Register'
        required: true
      security:
      - tokenAuth: []
      - cookieAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Register'
          description: ''
  /api/polls/:
    get:
      operationId: polls_list
      tags:
      - polls
      security:
      - tokenAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Poll'
          description: ''
    post:
      operationId: polls_create
      tags:
      - polls
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Poll'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Poll'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Poll'
        required: true
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Poll'
          description: ''
  /api/polls/{id}/:
    get:
      operationId: polls_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this poll.
        required: true
      tags:
      - polls
      security:
      - tokenAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Poll'
          description: ''
    put:
      operationId: polls_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this poll.
        required: true
      tags:
      - polls
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Poll'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Poll'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Poll'
        required: true
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Poll'
          description: ''
    patch:
      operationId: polls_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this poll.
        required: true
      tags:
      - polls
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedPoll'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedPoll'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedPoll'
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Poll'
          description: ''
    delete:
      operationId: polls_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this poll.
        required: true
      tags:
      - polls
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '204':
          description: No response body
  /api/polls/{id}/stats/:
    get:
      operationId: polls_stats_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this poll.
        required: true
      tags:
      - polls
      security:
      - tokenAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Poll'
          description: ''
  /api/polls/{id}/vote/:
    post:
      operationId: polls_vote_create
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this poll.
        required: true
      tags:
      - polls
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Poll'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Poll'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Poll'
        required: true
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Poll'
          description: ''
components:
  schemas:
    AboutApp:
      type: object
      properties:
        name:
          type: string
        emblem:
          type: string
        description:
          type: string
      required:
      - description
      - emblem
      - name
    AuthResponse:
      type: object
      properties:
        token:
          type: string
        user:
          $ref: '#/components/schemas/UserProfile'
      required:
      - token
      - user
    Choice:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        text:
          type: string
          maxLength: 200
        votes_count:
          type: integer
          readOnly: true
      required:
      - id
      - text
      - votes_count
    GenderEnum:
      enum:
      - female
      - male
      - other
      type: string
      description: |-
        * `female` - Female
        * `male` - Male
        * `other` - Other
    Login:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          writeOnly: true
      required:
      - email
      - password
    PatchedPoll:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 200
        description:
          type: string
        is_active:
          type: boolean
        created_by:
          type: string
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        choices:
          type: array
          items:
            $ref: '#/components/schemas/Choice'
        total_votes:
          type: integer
          readOnly: true
    PatchedUserProfile:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 150
        email:
          type: string
          format: email
          readOnly: true
        gender:
          $ref: '#/components/schemas/GenderEnum'
        birth_date:
          type: string
          format: date
    Poll:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 200
        description:
          type: string
        is_active:
          type: boolean
        created_by:
          type: string
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        choices:
          type: array
          items:
            $ref: '#/components/schemas/Choice'
        total_votes:
          type: integer
          readOnly: true
      required:
      - choices
      - created_at
      - created_by
      - id
      - title
      - total_votes
    Register:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 150
        email:
          type: string
          format: email
          maxLength: 254
        gender:
          $ref: '#/components/schemas/GenderEnum'
        birth_date:
          type: string
          format: date
        password:
          type: string
          writeOnly: true
          minLength: 8
      required:
      - birth_date
      - email
      - gender
      - id
      - name
      - password
    UserProfile:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 150
        email:
          type: string
          format: email
          readOnly: true
        gender:
          $ref: '#/components/schemas/GenderEnum'
        birth_date:
          type: string
          format: date
      required:
      - birth_date
      - email
      - gender
      - id
      - name
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
